# Generated by Django 4.2.5 on 2023-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['name', '-price'], 'verbose_name': 'Играшка', 'verbose_name_plural': 'Игрушки'},
        ),
        migrations.AddField(
            model_name='toy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
