# Generated by Django 4.2.5 on 2023-10-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_toy_options_toy_photo_alter_toy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('telephone', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='doc_toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('date_confirm', models.DateField()),
                ('data_expire', models.DateField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('toy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='example.toy')),
            ],
        ),
    ]
