# Generated by Django 4.2.5 on 2023-10-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_supplier_doc_toy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date_outload', models.DateTimeField(auto_now_add=True)),
                ('toy', models.ManyToManyField(to='example.toy')),
            ],
        ),
        migrations.CreateModel(
            name='Pos_order_toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_toys', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.order')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.toy')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='toy',
            field=models.ManyToManyField(through='example.Pos_order_toy', to='example.toy'),
        ),
    ]
