# Generated by Django 4.2.5 on 2023-10-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_order_supply_toys_pos_order_toy_order_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='example.supplier'),
        ),
    ]
