# Generated by Django 4.2.5 on 2023-11-21 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_orderitem_product_producttag_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
