# Generated by Django 4.2.5 on 2023-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_orderproduct_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
