# Generated by Django 4.2.5 on 2024-01-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_categorykb_orderkb_supplierkb_tagkb_productkb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorykb',
            options={'verbose_name': 'Категория_', 'verbose_name_plural': 'Категории_'},
        ),
        migrations.AlterModelOptions(
            name='deliveryitemkb',
            options={'verbose_name': 'Позиция поставки_', 'verbose_name_plural': 'Позиции поставки_'},
        ),
        migrations.AlterModelOptions(
            name='deliverykb',
            options={'verbose_name': 'Поставка_', 'verbose_name_plural': 'Поставки_'},
        ),
        migrations.AlterModelOptions(
            name='orderitemkb',
            options={'verbose_name': 'Позиция заказа_', 'verbose_name_plural': 'Позиции заказа_'},
        ),
        migrations.AlterModelOptions(
            name='orderkb',
            options={'verbose_name': 'Заказ_', 'verbose_name_plural': 'Заказы_'},
        ),
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'verbose_name': 'Характеристика товара_', 'verbose_name_plural': 'Характеристики товара_'},
        ),
        migrations.AlterModelOptions(
            name='productkb',
            options={'verbose_name': 'Товар_', 'verbose_name_plural': 'Товары_'},
        ),
        migrations.AlterModelOptions(
            name='supplierkb',
            options={'verbose_name': 'Поставщик_', 'verbose_name_plural': 'Поставщики_'},
        ),
        migrations.AlterModelOptions(
            name='tagkb',
            options={'verbose_name': 'Тег_', 'verbose_name_plural': 'Теги_'},
        ),
    ]
